# Render Blueprint for YTV2 YouTube Summarizer
# Updated version with modular architecture and web dashboard

services:
  - type: web
    name: ytv2-telegram-bot
    env: docker
    repo: https://github.com/Astrocyte74/YTV2
    branch: main
    dockerfilePath: ./Dockerfile
    
    # Health check endpoint
    healthCheckPath: /health
    
    # Environment variables
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: WEB_PORT
        value: "10000"
      - key: WEB_BASE_URL
        fromService:
          type: web
          name: ytv2-telegram-bot
          property: url
      
      # API Keys - Set these in Render dashboard
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_USER_ID  
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      
      # Application Configuration
      - key: LLM_SHORTLIST
        value: "fast"
      - key: DEFAULT_SUMMARY_TYPE
        value: "comprehensive"
      - key: MAX_TRANSCRIPT_LENGTH
        value: "50000"
      - key: HTML_REPORT_RETENTION_HOURS
        value: "168"
      - key: EXPORT_ENABLED
        value: "true"
      - key: WEB_DASHBOARD_ENABLED
        value: "true"
      - key: DEBUG_MODE
        value: "false"
    
    # Persistent disk for downloads, exports and cache
    disk:
      name: ytv2-storage
      mountPath: /app/data
      sizeGB: 2
    
    # Start command override
    startCommand: python telegram_bot.py