# Render Blueprint for YTV2 Dashboard
# Dashboard-only deployment for serving web interface

services:
  - type: web
    name: ytv2-dashboard
    env: docker
    repo: https://github.com/Astrocyte74/YTV2
    branch: main
    dockerfilePath: ./Dockerfile
    
    # Health check endpoint
    healthCheckPath: /health
    
    # Environment variables for dashboard-only deployment
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: WEB_PORT
        value: "10000"
      - key: PORT
        value: "10000"
      
      # Dashboard Configuration
      - key: RENDER_DASHBOARD_URL
        fromService:
          type: web
          name: ytv2-dashboard
          property: url
      - key: SYNC_SECRET
        sync: false  # Set this in Render dashboard for NAS sync security
      
      # Leave Telegram token empty for dashboard-only mode
      - key: TELEGRAM_BOT_TOKEN
        value: ""
      
      # Multi-user auth configuration (set in Render dashboard)
      - key: GOOGLE_CLIENT_IDS
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
    
    # Persistent disk for synced reports and audio files
    disk:
      name: ytv2-dashboard-storage
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    
    # Start command for dashboard server
    startCommand: python server.py
